apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dnyzit5ox-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:bed138b882244d562fb50ba1cb58f51fce5bd3ba@sha256:6b420d48eb7f2f85687d8c78facc22aaea6a434b9e9b33971aee97fc15a0caa0
          name: container-image
